services:

  app:
    build: .
    command: python -u app.py
    environment:
      - MONGODB_ROOT_USERNAME=root
      - MONGODB_ROOT_PASSWORD=pass
      - MONGODB_HOSTNAME=calendar_event_mongodb
      - MONGODB_DATABASE=calendar_event_db
      - MONGODB_PORT=27017
      - MONGODB_EVENTS_COLLECTION_NAME=events_collection
      - MONGODB_AUTHSOURCE=admin
    ports:
      - 8000:5000
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:latest
    hostname: calendar_event_mongodb
    environment:
      - MONGO_INITDB_DATABASE=calendar_event_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017